### ISSUE TITLE
Slack message shows step as: "undefined"

### ISSUE THREAD

**Issue by billcrook** [tobilg/marathon-slack#1]
Seeing this in slack channel:

> Deployment info
> The deployment `bec743f2-dc4f-42fd-b389-be6f096f5f4a` triggered the following steps:
> 1. undefined

Running on dc/os 1.7. Let me know if you need more info!

**Comment by tobilg** [comment]
@billcrook Thanks for reporting the issue. I see this as well with Marathon 0.15, but not with more recent versions. Seems like an API change... I'll try to figure out what has changed, but that's not too easy because the docs aren't versioned.

**Comment by tobilg** [comment]
Turns out there in fact was an API/message structure change from 0.15.x to >= 1.x. I fixed this and created a new version of the Docker image (0.1.3):

https://hub.docker.com/r/tobilg/marathon-slack/tags/

If you encounter other problems please open an issue again. Thanks!
