### ISSUE TITLE
Add a healthcheck to the Universe package

### ISSUE THREAD

**Issue by ssk2** [tobilg/marathon-slack#10]
Looks like the DC/OS package doesn't have a healthcheck. This would be an easy fix - currently there is no health reported. 

![image](https://cloud.githubusercontent.com/assets/355705/25914023/b3e45d70-3571-11e7-8d87-7574b1ee40f3.png)

**Comment by tobilg** [comment]
Well, the only health check that could (maybe) work would be a command health check which looks for the actual Node.js process. It's not exposing/using a http API

**Comment by tobilg** [comment]
A health check endpoint was added by https://github.com/tobilg/marathon-slack/commit/af88c18c77ed0563b90b660750df986c03b310fa. Closing.
