### ISSUE TITLE
Add application information to deployment messages

### ISSUE THREAD

**Issue by ssk2** [tobilg/marathon-slack#11]
It'd be helpful to see what application is being deployed when getting status messages. Currently it's hard to correlate the deployment IDs to underlying applications (especially if the deployment completes - it's difficult to find out information from the UI, you have to use the API - which is a lot of effort).

```
[11:10] 
Deployment success
The deployment `b5e6bf30-2455-4388-850f-963fe370fddc` was completed successfully at `2017-05-10 18:10:16.636`
Today at 11:10 AM```

**Comment by tobilg** [comment]
A deployment is not bound to a single app afaik. What would you like to see if there are multiple apps affected?

**Comment by protetore** [comment]
It would be nice to see the service (app) names affected by this deployment, so the alert could be directed to the right person.

+1

**Comment by tobilg** [comment]
As I wrote before, a deployment is not necessarily bound to a single app (see https://mesosphere.github.io/marathon/docs/event-bus.html#deployments). The steps are already shown, so it's not really clear what the requirement is. Can you please elaborate @protetore @rafaelspecta?

**Comment by tobilg** [comment]
Closing this now, please reopen with further details if necessary...
