### ISSUE TITLE
Not able to deploy marathon-slack with latest version.

### ISSUE THREAD

**Issue by shashanks93** [tobilg/marathon-slack#16]
I'm trying to deploy  **marathon/slack** latest version  i.e.  **toblig/marathon-slack:0.4.3**
![image](https://user-images.githubusercontent.com/4211679/30431886-a3463b76-997d-11e7-8674-9595a204c95f.png)
but not able to deploy. Every time i'm trying to deploy with latest version, deployment gets suspended.
I checked in the log but couldn't figure out what's the issue 

> events.js:160
      throw er; // Unhandled 'error' event
      ^

> Error: Listen EADDRNOTAVAIL 172.31.29.125:31748
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at Server._listen2 (net.js:1245:19)
    at listen (net.js:1294:10)
    at net.js:1404:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:81:10)

> npm ERR! Linux 3.13.0-119-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! marathon-slack@0.4.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the marathon-slack@0.4.0 start script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the marathon-slack package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs marathon-slack
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls marathon-slack
npm ERR! There is likely additional logging output above.

> npm  ERR! Please include the following file with any support request:
npm ERR!     /usr/local/marathon-slack/npm-debug.log

Though i'm able to deploy the earlier version till **`toblig/marathon-slack:0.3.1`** but after this version i'm not able to deploy.
I'm trying to use the **APP_ID_REGEXES** env variable to filter the events which is only available in the latest release

Any help regarding this issue would be appreciable.

**Comment by tobilg** [comment]
You don't seem to deploy this as outlined at https://github.com/tobilg/marathon-slack#installing-via-marathon Can you check?

**Comment by shashanks93** [comment]
Hi,
I've been using the same as it is outlined in the documentation. And moreover, it's working fine upto **version 0.3.1** but beyond it's failing.
Please find the snippet of the json.

{
 ` "id": "/monitoring/marathon-slack",`
`  "cmd": null,`
 ` "cpus": 0.2,`
`  "mem": 200,`
 ` "disk": 0,`
`  "instances": 1,`
 ` "container":` {
`    "type": "DOCKER",`
`    "volumes": [],`
`    "docker": `{
 `     "image": "tobilg/marathon-slack:0.3.1",`
`      "network": "BRIDGE",`
 `     "portMappings":` [
        {
`          "containerPort": 9110,`
`          "hostPort": 0,`
`          "servicePort": 10053,`
`          "protocol": "tcp",`
`          "labels": {}`
        }
      ],
`      "privileged": false,`
`      "parameters": [],`
`      "forcePullImage": true`
    }
  },
  "env": {
`    "SLACK_CHANNEL": "#Slack_Channel",`
`    "EVENT_TYPES"`: `"deployment_info,deployment_success,deployment_failed,failed_health_check_event,unhealthy_task_kill_event",`
   ` "LOG_LEVEL": "debug",`
  ` "VERSION": "__version__",`
`    "MIST_ENV": "production",`
`    "SLACK_WEBHOOK_URL": "#Webhook Url",`
`    "ENV": "production",`
`    "MARATHON_HOST": "#Some_Host",`
`    "APP_ID_REGEXES": "/le/*,/cloud-seeding-*,/dizzy*"`
  },
  "labels": {
`    "traefik.domain": "#######"`
  },
  "portDefinitions": [
    {
`      "port": 10053,`
`      "protocol": "tcp",`
`      "labels": {}`
    }
  ],
  "uris": [
`    "#Some Url"`
  ],
  "fetch": [
    {
`      "uri": "#Some Url",`
`      "extract": true,`
`      "executable": false,`
`      "cache": false`
    }
  ]
}

**Comment by tobilg** [comment]
I'm sorry, but you didn't @shashanks93. The guide's JSON isn't using BRIDGE networking. Try it with HOST networking instead.

See https://github.com/tobilg/marathon-slack/blob/master/index.js#L56-L57

Also, I'm not really sure why you'd need to fetch some URIs as well.

**Comment by shashanks93** [comment]
We fetch login details from URI's .
And also why can't we use  `network: Bridge `?
what if i want to use network Bridge network type instead of Host ?

**Comment by tobilg** [comment]
Not sure what you need login details for, because the image is public. But that is not really related to your problem. The error message means that the Node.js app can't bind to the IP address specified (see https://stackoverflow.com/a/32634222/1603357). 

> Error: Listen EADDRNOTAVAIL 172.31.29.125:31748

Are you sure that this is a valid Docker bridge networking IP? What's the reasoning behind BRIDGE networking? I don't really see a problem with HOST networking.

I don't really think that there's a problem with marathon-slack, because it's working without problems for me if I use the provided Marathon app definition.

**Comment by shashanks93** [comment]
Actually i am trying to separate the messages for prod and stage. And there are 100 of services running from marathon, but i want when ever a deployment happens or any health check fails, i should get notification on slack.
I tried using **APP_ID_REGEXES**, but since i have this much of services running it's not preferable to use it.
And there are few services being deployed by jenkins in marathon in every 1 hour. So, the slack channel is becoming quite noisy because of the notification being sent in every 1 hour.
So,is there any way to **black list** the notification of services which i don't need or being triggered by jenkins on marathon so that i don't get the messages from those services ?

**Comment by tobilg** [comment]
There's currently no way to blacklist applications. PRs are welcome though.

Regarding PROD and STAGE, I'd suggest that you create separate Slack channels and let each environment post it's messages to the individual channel...

The better way would probably be to limit the types of events to the really necessary ones. See

* https://github.com/tobilg/marathon-slack#event-types
* https://mesosphere.github.io/marathon/docs/event-bus.html

**Comment by shashanks93** [comment]
Thanks.
Though what i have thought of doing is, i'll use **marathon groups**.
And i'll group all the application which i don't require and will not pass those groups with the marathon slack. By doing this might solve the problem.
Because my requirement is to filter out the notification of some services which is being triggered automatically which are unnecessarily creating noise in the slack channels after every 1 hour.
So i think that might be the one of the approach.
Let me know your understanding on this or this any better way of doing this.
