### ISSUE TITLE
error in APP_ID_REGEXES

### ISSUE THREAD

**Issue by chaitup** [tobilg/marathon-slack#17]
I gave APP_ID_REGEXES as *<APPID>*. I am getting below error.
 
/usr/local/marathon-slack/lib/MarathonSlackBridge.js:71
                console.log("The provided RegExp " + regExp + " isn't a valid regular expression!");
                                                     ^

ReferenceError: regExp is not defined
    at new MarathonSlackBridge (/usr/local/marathon-slack/lib/MarathonSlackBridge.js:71:54)
    at Object.<anonymous> (/usr/local/marathon-slack/index.js:14:29)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3

npm ERR! Linux 3.10.0-514.26.2.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! marathon-slack@0.4.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the marathon-slack@0.4.1 start script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the marathon-slack package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs marathon-slack
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls marathon-slack
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/marathon-slack/npm-debug.log

**Comment by tobilg** [comment]
See https://dcos-community.slack.com/archives/C2GGYALHL/p1509035674000410

**Comment by nicladas** [comment]
@tobilg The error is pointing to MarathonSlackBridge.js:71 `ReferenceError: regExp is not defined`, not that there is a problem with the regular expression itself.

**Comment by tobilg** [comment]
Yep, that seems to be a big in the code, but the line is only triggered when an invalid RegExp is passed in @nicladas

**Comment by nicladas** [comment]
Understood @tobilg. I would offer a PR, but you may be able to resolve it faster than I could.

**Comment by tobilg** [comment]
This was fixed by #18. A PR for the DC/OS Universe will be created. Closing.

**Comment by tobilg** [comment]
Universe PR is here: https://github.com/mesosphere/universe/pull/1494
