### ISSUE TITLE
Unable to run the app with MESOS_HTTP health check

### ISSUE THREAD

**Issue by idanto** [tobilg/marathon-slack#22]
I tried to use the new best practice health check of marathon - `MESOS_HTTP`.
This health check delegate the health check to the mesos agent which execute the health check with localhost (127.0.0.1).

Currently, the app is listening to the IP address of the host only
https://github.com/tobilg/marathon-slack/blob/494f5ba27df507ad0d01f44f17aac967d3e9e1f7/index.js#L56

The solution to support the new health check is to remove the IP address from here:
https://github.com/tobilg/marathon-slack/blob/494f5ba27df507ad0d01f44f17aac967d3e9e1f7/index.js#L71

The marathon based health checks deprecated and will be removed by [Marathon docs](https://mesosphere.github.io/marathon/docs/health-checks.html)
```
Important: Marathon-based health checks are deprecated and will be removed in a future version. See the 1.4.0 release notes for more information.
```

**Comment by tobilg** [comment]
Thanks again. To be honest, I don't see immediate action to be taken on this, as Marathon still supports health checks. As far as I know removing the concrete ip address will make express.js listen on all addresses, which is not the behavior I desire for this application.

**Comment by idanto** [comment]
It is true that Marathon health checks are still supported but the support for Mesos health check is needed for the long run.
May I ask why to listen to all IP addresses is something you don't desire for this app?

Another option is to add another `app.listen` function that will listen to the localhost IP and a second port for Mesos health checks if specific env var is passed to the app (something like MESOS_HEALTH_CHECK: true), What do you think about that?

This feature is important to us because we are trying to reduce as much load as we can from the marathon masters.

**Comment by tobilg** [comment]
As the Express server is just there for the health checking of the app (https://github.com/tobilg/marathon-slack/blob/master/index.js#L61), I'd think that it should be fine to merge your PR, as it'll then bind to `0.0.0.0` by default afaik.

That should then work with both Marathon and Mesos health checks.

**Comment by idanto** [comment]
@tobilg Thanks, you are right it will work for both Marathon and Mesos health checks.

We can do another thing, we can bind the same port to both IP's the `$HOST` and `127.0.0.1` with two different app.listen lines.

```js
const host_server = app.listen(apiOptions.port, apiOptions.ipAddress, callbackFunction);
const localhost_server = app.listen(apiOptions.port, '127.0.0.1', callbackFunction);
```

This code will solve the issue and keep the same behavior you like.
If you would like to do that, let me know and I will edit the PR, If not I will appreciate if you can approve the exists code the in PR.

**Comment by tobilg** [comment]
I don't really like the idea of having two servers... I'll merge the PR and release a new Docker image.

**Comment by tobilg** [comment]
Docker image with tag `0.4.6` is being built.

**Comment by idanto** [comment]
Thank you @tobilg
