### ISSUE TITLE
Ability to filter by group and/or app

### ISSUE THREAD

**Issue by alenkacz** [tobilg/marathon-slack#3]
I would like to filter events by an apo group or name of the app.

I am happy to submit PR if that sounds good...

**Comment by tobilg** [comment]
Sounds interesting...! How would you imagine the definition of the filters? Comma-separated list? Would you have two filters, one for apps and one for groups?

**Comment by alenkacz** [comment]
Exactly. Comma separated, two different filters.

**Comment by tobilg** [comment]
Ok, sounds good :-) I'd be happy to receive a PR. Do you use this on plain Mesos/Marathon, or DC/OS?

**Comment by tobilg** [comment]
Sorry, one more thing: It would be great if the filters can be defined via environment variable, as then others already work. Thanks!

**Comment by tobilg** [comment]
Another requirement would be that there needs to be a default value \* which signals that all app or groups shall be used. This is necessary for the DC/OS Universe package, which needs default values.

**Comment by tobilg** [comment]
Hi @alenkacz, just a quick question: Are you still interested in providing a PR? Otherwise I'd close this issue because I currently don't have time to implement it myself. Thanks!

**Comment by alenkacz** [comment]
@tobilg yes, sorry. I am busy eith another project but I will finish this soon

**Comment by tobilg** [comment]
No problem @alenkacz! Just wanted to check whether it's still relevant... Thanks for your efforts!

**Comment by tobilg** [comment]
Close due to inactivity.
