### ISSUE TITLE
Health check for marathon-slack when running inside marathon?

### ISSUE THREAD

**Issue by eyalzek** [tobilg/marathon-slack#7]
I can run a script health check to see if the process is running, but this will pass even if the process is logging errors as far as I understand it. Is there a more stable/clever way to subscribe a health check?

**Comment by tobilg** [comment]
Not sure I understand... Are you talking about health checking `marathon-slack`, or getting health status updates, or something else? Can you please elaborate?

**Comment by eyalzek** [comment]
A health check checking `marathon-slack`, e.g:

```
{
  "id": "/marathon-slack",
  "cpus": 0.1,
  "mem": 128,
  "disk": 0,
  "instances": 1,
  "container": {
    "type": "DOCKER",
    "docker": {
      "image": "tobilg/marathon-slack:0.3.0",
      "network": "HOST",
      "privileged": false,
      "parameters": [],
      "forcePullImage": true
    }
  },
  "healthChecks": [
    {
      "portIndex": 0,
      "protocol": "HTTP",
      "path": "/",
      "gracePeriodSeconds": 60,
      "intervalSeconds": 10,
      "timeoutSeconds": 5,
      "maxConsecutiveFailures": 0
    }
  ],
  "env": {
    "MARATHON_HOST": "marathon",
    "SLACK_WEBHOOK_URL": "..."
  }
}
```

which is irrelevant in this case because no port is exposed. As I mentioned, I can have a `SCRIPT` type check and check something like `ps ax |grep [m]arthon-slack` or so, but I'm not sure that's the way to go

**Comment by tobilg** [comment]
Ah, I see... It's not using/exposing a HTTP API as you already mentioned. I guess a `COMMAND` health check is the way to go.

**Comment by eyalzek** [comment]
The thing is, there isn't a process named `marathon-slack` that I can grep the output of `ps ax` for.. there are several processes running:

```
/usr/local/marathon-slack # ps ax
PID   USER     TIME   COMMAND
    1 root       0:00 npm
   14 root       0:00 sh -c node index.js
   15 root       0:09 node index.js
   51 root       0:00 /bin/sh
   59 root       0:00 ps ax
```

not sure which one would be the correct one to base a health check on. What do you think?

**Comment by tobilg** [comment]
I think it is `node index.js`.

**Comment by eyalzek** [comment]
Ok, thanks. Currently going with:

```
  "healthChecks": [
    {
      "protocol": "COMMAND",
      "command": {"value": "ps -o comm |grep '[n]ode'"}
    }
  ]
```

I guess this can be closed.
