### ISSUE TITLE
Does not work properly when forked

### ISSUE THREAD

**Issue by cookandy** [tobilg/marathon-slack#8]
This issue is really strange to me - I hope I'm not missing something obvious.  

I forked this repo and setup an [automated docker build](https://hub.docker.com/r/acook/marathon-slack/).  However, when I run my version of the build I get:

```
Got an error on 1486081237.669:
{"type":"error"}
Got an error on 1486081238.7:
{"type":"error"}
Got an error on 1486081239.704:
{"type":"error"}
Got an error on 1486081240.724:
{"type":"error"}
Got an error on 1486081241.735:
{"type":"error"}
Got an error on 1486081242.754:
{"type":"error"}
Got an error on 1486081243.76:
{"type":"error"}
```

With your build, however, it works correctly and I see `Subscribed to the Marathon Event Bus`.

I tried building the `0.3.0` tag and ran into the same issue.  The only line I'm changing in the marathon deploy file is:

```
-  "image": "tobilg/marathon-slack:0.3.0"
+  "image": "acook/marathon-slack:0.3.0"
```

Any ideas why?

**Comment by tobilg** [comment]
Did you change something else? I mean within the application?

**Comment by cookandy** [comment]
No, not a thing. You can compare your repo to mine and see that then docker automated build is the same as yours. Just wondering, do you experience the same when you use my image? Have you tried rebuilding your image to see if you can reproduce?

**Comment by cookandy** [comment]
The only thing I can think of is that the `mhart/alpine-node:6` image [has recently changed.](https://hub.docker.com/r/mhart/alpine-node/tags/)

**Comment by arun-eli** [comment]
I get same issue as @cookandy even when I use @tobilg 's image directly.

**Comment by tobilg** [comment]
@arun-eli @cookandy I tested the `0.3.1` [tag](https://hub.docker.com/r/tobilg/marathon-slack/tags/), and it works flawlessly via the default app JSON as outlined at https://github.com/tobilg/marathon-slack#installing-via-marathon

So I really have a problem figuring out what your problems could be.

**Comment by arun-eli** [comment]
@tobilg What is the marathon/mesos version you are using? I am using this marathon json with just one change that is MARATHON_HOST but still does not work for me.

**Comment by tobilg** [comment]
Are you sure that the MARATHON_HOST is reachable from every agent node, e.g. via curl, with the right port? @arun-eli?

I'm using DC/OS 1.8 personally.

**Comment by arun-eli** [comment]
@tobilg Yes marathon host (using ZooKeeper) us reachable using cURL at port 8080.

**Comment by arun-eli** [comment]
@tobilg Under what condition, do you log this error? 
_Got an error on 1486081242.754:
{"type":"error"}
Got an error on 1486081243.76:
{"type":"error"}_

**Comment by arun-eli** [comment]
Update: I removed "http" prefix in MARATHON_HOST and now I get "Subscribed to the Marathon Event Bus"

**Comment by arun-eli** [comment]
@tobilg I am wondering how much customization I can do. For example, I wand start/stop app go to slack channel1 and apps going out of memory and TASK change from TASK_RUNNING to TASK_FAILED go to slack channel2. Is it possible?

**Comment by tobilg** [comment]
No, that's currently not possible

**Comment by tobilg** [comment]
@cookandy Can you also confirm that if you're using a hostname or IP only, without a protocol prefix, it works? If so please close the ticket accordingly. Thanks.

**Comment by tobilg** [comment]
@arun-eli PRs are very welcome if you want this functionality added...

**Comment by arun-eli** [comment]
@tobilg Sure. I will. There is another issue. When a docker container (part of marathon task) gets restarted due to out of memory, I only health update event. It does not get the app name. Are you aware of this issue already?
![image](https://cloud.githubusercontent.com/assets/17836676/23816385/5f37aa3e-05a1-11e7-8f79-438c8195e289.png)

**Comment by arun-eli** [comment]
I meant to say, we need more information for events as shown here - https://mesosphere.github.io/marathon/docs/event-bus.html

**Comment by tobilg** [comment]
That is stated at https://github.com/tobilg/marathon-slack#event-types @arun-eli and it's not related to this issue.
